# Generated by Django 5.1.4 on 2025-06-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_user',
            new_name='update_user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='updated_user',
            new_name='update_user',
        ),
    ]
