# Generated by Django 4.1 on 2024-12-26 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryMst',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ItemMst',
            new_name='Item',
        ),
    ]
