# Generated by Django 4.1 on 2024-12-27 00:40

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_alter_category_created_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_cd',
            field=models.CharField(max_length=255, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='アイテムコード'),
        ),
    ]
