# Generated by Django 5.1.4 on 2025-09-22 12:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_category_nm', models.CharField(max_length=255, verbose_name='商品カテゴリ')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ['product_category_nm'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_cd', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z_-]+$', '半角英数字・ハイフン・アンダースコアのみ使用できます。')], verbose_name='商品コード')),
                ('product_nm', models.CharField(max_length=255, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品説明')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='価格')),
                ('start_date', models.DateTimeField(default=datetime.datetime(1899, 12, 31, 15, 0, tzinfo=datetime.timezone.utc), verbose_name='適用開始日')),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 30, 15, 0, tzinfo=datetime.timezone.utc), verbose_name='適用終了日')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_mst.productcategory', verbose_name='商品カテゴリ')),
            ],
            options={
                'ordering': ['product_cd', 'start_date'],
                'constraints': [models.UniqueConstraint(fields=('product_cd', 'start_date', 'end_date'), name='uq_product_cd_period')],
            },
        ),
    ]
