# Generated by Django 5.1.4 on 2025-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('start_date', models.DateField(verbose_name='適用開始日')),
                ('end_date', models.DateField(verbose_name='適用終了日')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品説明')),
            ],
            options={
                'ordering': ['product_name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product_category_name', models.CharField(max_length=255, unique=True, verbose_name='商品カテゴリ')),
            ],
            options={
                'ordering': ['product_category_name'],
            },
        ),
    ]
