# Generated by Django 5.1.4 on 2025-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(verbose_name='適用終了日'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(verbose_name='適用開始日'),
        ),
    ]
