# Generated by Django 5.1.4 on 2025-09-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rounding_method',
            field=models.CharField(choices=[('floor', '切り捨て'), ('ceil', '切り上げ'), ('half_up', '四捨五入')], default='floor', max_length=20, verbose_name='端数処理方法'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='単価'),
        ),
    ]
