# Generated by Django 5.1.4 on 2025-10-02 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0002_initial'),
        ('tenant_mst', '0002_remove_tenant_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uq_product_name_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_date',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name', 'tenant'), name='uq_product_name_period'),
        ),
    ]
