# Generated by Django 5.1.4 on 2025-09-29 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0002_initial'),
        ('tenant_mst', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name', 'start_date']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['product_category_name']},
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uq_product_code_period',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_category_name',
            new_name='product_category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('tenant', 'product_category_name')},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name', 'start_date', 'end_date', 'tenant'), name='uq_product_name_period'),
        ),
    ]
