# Generated by Django 5.1.4 on 2025-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0002_product_rounding_method_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4, verbose_name='税率'),
        ),
    ]
