# Generated by Django 5.1.4 on 2025-10-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=20, verbose_name='単位'),
            preserve_default=False,
        ),
    ]
