# Generated by Django 5.1.4 on 2025-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0003_product_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rounding_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
    ]
