# Generated by Django 5.1.4 on 2025-10-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0004_rename_price_product_unit_price_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='単価'),
        ),
    ]
