# Generated by Django 5.1.4 on 2025-09-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0005_product_tenant_productcategory_tenant'),
        ('tenant_mst', '0003_alter_tenant_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント'),
            preserve_default=False,
        ),
    ]
