# Generated by Django 5.1.4 on 2025-10-14 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0005_alter_product_unit_price'),
        ('tenant_mst', '0002_remove_tenant_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name': '商品', 'verbose_name_plural': '商品マスタ'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['product_category_name'], 'verbose_name': '商品カテゴリ', 'verbose_name_plural': '商品カテゴリマスタ'},
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uq_product_name_period',
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_mst.productcategory', verbose_name='商品カテゴリ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_category_name',
            field=models.CharField(max_length=255, verbose_name='商品カテゴリ'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name', 'tenant'), name='uq_product_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'product_category_name'), name='uq_tenant_product_category_name'),
        ),
    ]
