# Generated by Django 5.1.4 on 2025-09-26 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0006_alter_product_tenant_alter_productcategory_tenant'),
        ('tenant_mst', '0003_alter_tenant_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uq_product_cd_period',
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('tenant', 'product_category_nm')},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_cd', 'start_date', 'end_date', 'tenant'), name='uq_product_cd_period'),
        ),
    ]
