# Generated by Django 5.1.4 on 2025-10-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0007_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='商品の仕様や補足情報などを255文字以内で記入できます。（任意）', max_length=255, null=True, verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='商品のカテゴリを選択してください。（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_mst.productcategory', verbose_name='商品カテゴリ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='100文字以内で入力してください。重複登録はできません。', max_length=100, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(help_text='数量に対する単位を20文字以内で入力してください。例：個、箱、kgなど', max_length=20, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='数値で入力してください。小数第2位まで指定できます。（任意）', max_digits=10, null=True, verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_category_name',
            field=models.CharField(help_text='100文字以内で入力してください。', max_length=100, verbose_name='商品カテゴリ'),
        ),
    ]
