# Generated by Django 5.1.4 on 2025-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0008_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='数値で入力してください。小数第2位まで指定できます。（任意）', max_digits=12, null=True, verbose_name='単価'),
        ),
    ]
