# Generated by Django 5.1.4 on 2025-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0009_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='商品の仕様や補足情報などを255文字以内で記入できます。（任意）', null=True, verbose_name='商品説明'),
        ),
    ]
