# Generated by Django 5.1.4 on 2025-10-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mst', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='数量に対する単位を20文字以内で入力してください。例：個、箱、kgなど', max_length=20, null=True, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='数値で入力してください。小数第2位まで指定できます。（任意）', max_digits=12, verbose_name='単価'),
            preserve_default=False,
        ),
    ]
