STATUS_CODE_DRAFT = 'DRAFT'
STATUS_CODE_SUBMITTED = 'SUBMITTED'
STATUS_CODE_APPROVED = 'APPROVED'
STATUS_CODE_REJECTED_IN = 'REJECTED_IN'
STATUS_CODE_CONFIRMED = 'CONFIRMED'
STATUS_CODE_REJECTED_OUT = 'REJECTED_OUT'
STATUS_CODE_ORDER_SUBMITTED = 'ORDER_SUBMITTED'
STATUS_CODE_ORDER_APPROVED = 'ORDER_APPROVED'
STATUS_CODE_ORDER_REJECTED_IN = 'ORDER_REJECTED_IN'
STATUS_CODE_ORDER_CONFIRMED = 'ORDER_CONFIRMED'
STATUS_CODE_ORDER_REJECTED_OUT = 'ORDER_REJECTED_OUT'
STATUS_CODE_CANCELED = 'CANCELED'
STATUS_CODE_RETAKE = 'RETAKE'

STATUS_CHOICES = (
    (STATUS_CODE_DRAFT, '仮作成'),
    (STATUS_CODE_SUBMITTED, '社内承認待ち'),
    (STATUS_CODE_APPROVED, '社内承認済'),
    (STATUS_CODE_REJECTED_IN, '社内却下'),
    (STATUS_CODE_CONFIRMED, '顧客承諾済'),
    (STATUS_CODE_REJECTED_OUT, '顧客却下'),
    (STATUS_CODE_ORDER_SUBMITTED, '注文書承認待ち'),
    (STATUS_CODE_ORDER_APPROVED, '注文書承認済'),
    (STATUS_CODE_ORDER_REJECTED_IN, '注文書却下'),
    (STATUS_CODE_ORDER_CONFIRMED, '契約済'),
    (STATUS_CODE_ORDER_REJECTED_OUT, '顧客発注書却下'),
    # ('READY_SHIP', '出荷待ち'),
    # ('SHIPPED', '出荷済'),
    # ('BILLED', '請求済'),
    # ('PAID', '入金済'),
    (STATUS_CODE_CANCELED, 'キャンセル'),
)

ACTION_CODE_OUTPUT_QUATATION_IN = 'OUTPUT_QUATATION_IN'
ACTION_CODE_OUTPUT_QUATATION_OUT = 'OUTPUT_QUATATION_OUT'
ACTION_CODE_OUTPUT_ORDER_IN = 'OUTPUT_ORDER_IN'
ACTION_CODE_OUTPUT_ORDER_OUT = 'OUTPUT_ORDER_OUT'