#--------------------------
# 受注ステータスコード
#--------------------------
STATUS_CODE_DRAFT = 'DRAFT'
STATUS_CODE_QUOTATION_SUBMITTED = 'QUOTATION_SUBMITTED'
STATUS_CODE_QUOTATION_APPROVED = 'QUOTATION_APPROVED'
STATUS_CODE_QUOTATION_REJECTED_IN = 'QUOTATION_REJECTED_IN'
STATUS_CODE_QUOTATION_CONFIRMED = 'QUOTATION_CONFIRMED'
STATUS_CODE_QUOTATION_REJECTED_OUT = 'QUOTATION_REJECTED_OUT'
STATUS_CODE_ORDER_SUBMITTED = 'ORDER_SUBMITTED'
STATUS_CODE_ORDER_APPROVED = 'ORDER_APPROVED'
STATUS_CODE_ORDER_REJECTED_IN = 'ORDER_REJECTED_IN'
STATUS_CODE_ORDER_CONFIRMED = 'ORDER_CONFIRMED'
STATUS_CODE_ORDER_REJECTED_OUT = 'ORDER_REJECTED_OUT'
STATUS_CODE_CANCELED = 'CANCELED'
STATUS_CODE_QUOTATION_RETAKE = 'QUOTATION_RETAKE'
STATUS_CODE_ORDER_RETAKE = 'ORDER_RETAKE'

#--------------------------
# 受注ステータスコード：受注ステータス名称
#--------------------------
STATUS_CHOICES = (
    (STATUS_CODE_DRAFT, '見積書：仮作成'),
    (STATUS_CODE_QUOTATION_SUBMITTED, '見積書：提出済'),
    (STATUS_CODE_QUOTATION_APPROVED, '見積書：社内承認済'),
    (STATUS_CODE_QUOTATION_CONFIRMED, '見積書：顧客承認済'),
    (STATUS_CODE_QUOTATION_REJECTED_IN, '見積書：社内却下'),
    (STATUS_CODE_QUOTATION_REJECTED_OUT, '見積書：顧客却下'),
    (STATUS_CODE_ORDER_SUBMITTED, '注文書：提出済'),
    (STATUS_CODE_ORDER_APPROVED, '注文書：社内承認済'),
    (STATUS_CODE_ORDER_CONFIRMED, '契約済'),
    (STATUS_CODE_ORDER_REJECTED_IN, '注文書：社内却下'),
    (STATUS_CODE_ORDER_REJECTED_OUT, '注文書：顧客却下'),
    # ('READY_SHIP', '出荷待ち'),
    # ('SHIPPED', '出荷済'),
    # ('BILLED', '請求済'),
    # ('PAID', '入金済'),
    (STATUS_CODE_CANCELED, 'キャンセル'),
)

#--------------------------
# アクション名称
#--------------------------
ACTION_CODE_OUTPUT_QUOTATION_IN = 'OUTPUT_QUOTATION_IN'
ACTION_CODE_OUTPUT_QUOTATION_OUT = 'OUTPUT_QUOTATION_OUT'
ACTION_CODE_OUTPUT_ORDER_IN = 'OUTPUT_ORDER_IN'
ACTION_CODE_OUTPUT_ORDER_OUT = 'OUTPUT_ORDER_OUT'