# Generated by Django 5.1.4 on 2025-06-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='都道府県'),
        ),
    ]
