# Generated by Django 5.1.4 on 2025-09-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.CharField(choices=[('0', 'システム'), ('1', '管理者'), ('2', '一般'), ('3', '参照')], default='3', max_length=3, verbose_name='権限'),
        ),
    ]
