# Generated by Django 5.1.4 on 2025-09-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customuser_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '男性'), ('1', '女性'), ('2', 'その他')], max_length=1, null=True, verbose_name='性別'),
        ),
    ]
