# Generated by Django 5.1.4 on 2025-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customuser_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ユーザー名（カナ）'),
        ),
    ]
