# Generated by Django 4.1 on 2024-12-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privilege',
            field=models.CharField(choices=[('0', 'SUPER'), ('1', 'NORMAL'), ('2', 'REFERENCE')], db_column='権限', default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(db_column='誕生日', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('0', 'MEALE'), ('1', 'FEMEALE'), ('2', 'OTHER')], db_column='性別', default='0', max_length=1),
        ),
    ]
