# Generated by Django 4.1 on 2024-12-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_customuser_privilege_alter_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('0', 'MEALE'), ('1', 'FEMEALE'), ('2', 'OTHER')], default='0', max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.CharField(choices=[('0', 'SUPER'), ('1', 'NORMAL'), ('2', 'REFERENCE')], default='2', max_length=1, verbose_name='権限'),
        ),
    ]
