# Generated by Django 5.1.4 on 2025-10-14 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_customuser_username_kana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='半角数字7桁で入力してください', regex='^\\d{7}$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='半角数字のみで入力してください', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, verbose_name='ユーザー名'),
        ),
    ]
