# Generated by Django 5.1.4 on 2025-10-14 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_customuser_address_alter_customuser_address2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザーマスタ'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, help_text='番地などを100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, help_text='建物名・部屋番号などを150文字以内で入力してください。（任意）', max_length=150, null=True, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='生年月日を「YYYY-MM-DD」形式で入力してください。（任意）', null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='市区町村名を50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='半角英数字で正しいメール形式を入力してください。例：info@example.com', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_end_date',
            field=models.DateField(blank=True, help_text='退職済みの場合は退職日を入力してください。（任意）', null=True, verbose_name='退職日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(choices=[('1', '在職中'), ('2', '休職中'), ('3', '退職済み')], default='1', help_text='現在の雇用状態を選択してください。', max_length=1, verbose_name='雇用状態'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '男性'), ('1', '女性'), ('2', 'その他')], help_text='該当する性別を選択してください。（任意）', max_length=1, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.CharField(choices=[('0', 'システム'), ('1', '管理者'), ('2', '一般'), ('3', '参照')], default='3', help_text='ユーザーの操作権限を選択してください。', max_length=3, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, help_text='都道府県名を10文字以内で入力してください。（任意）', max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, help_text='数字とハイフンのみ使用できます。例：090-1234-5678（任意）', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='100文字以内で入力してください。', max_length=100, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_kana',
            field=models.CharField(blank=True, help_text='カタカナ100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='ユーザー名（カナ）'),
        ),
    ]
