# Generated by Django 5.1.4 on 2025-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_customuser_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tenant',
        ),
    ]
