# Generated by Django 5.1.4 on 2025-10-15 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_customuser_options_alter_customuser_address_and_more'),
        ('tenant_mst', '0003_remove_tenant_tel_number_tenant_contact_tel_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(help_text='100文字以内で入力してください。', max_length=100, unique=True, verbose_name='グループ名')),
                ('description', models.TextField(blank=True, help_text='グループの説明を入力してください。（任意）', null=True, verbose_name='説明')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'ユーザーグループ',
                'verbose_name_plural': 'ユーザーグループマスタ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups_custom',
            field=models.ManyToManyField(blank=True, help_text='ユーザーが所属するグループを選択してください。（複数選択可）', related_name='users', to='register.usergroup', verbose_name='所属グループ'),
        ),
    ]
