# Generated by Django 5.1.4 on 2025-09-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_customuser_tenant'),
        ('tenant_mst', '0003_alter_tenant_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenant_mst.tenant', verbose_name='所属テナント'),
            preserve_default=False,
        ),
    ]
