# Generated by Django 4.1 on 2024-12-25 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_customuser_address_customuser_postal_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='住所2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='市町村'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'MEALE'), ('1', 'FEMEALE'), ('2', 'OTHER')], max_length=1, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_cd',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
    ]
