# Generated by Django 5.1.4 on 2025-10-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_usergroup_customuser_groups_custom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['group_name'], 'verbose_name': 'ユーザーグループ', 'verbose_name_plural': 'ユーザーグループマスタ'},
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='name',
            new_name='group_name',
        ),
    ]
