# Generated by Django 5.1.4 on 2025-09-29 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_customuser_tenant'),
        ('tenant_mst', '0003_alter_tenant_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='退職日'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(choices=[('1', '在職中'), ('2', '休職中'), ('3', '退職済み')], default='1', max_length=1, verbose_name='雇用状態'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_cd',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='半角数字7桁で入力してください', regex='^\\d{7}$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.CharField(choices=[('0', '特権'), ('1', '一般'), ('2', '参照'), ('3', 'ゲスト')], default='3', max_length=3, verbose_name='権限'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント'),
        ),
    ]
