# Generated by Django 5.1.4 on 2025-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_usergroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups_custom',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='ユーザーが所属するグループを選択してください。（複数選択可）', related_name='users', to='register.usergroup', verbose_name='所属グループ'),
        ),
    ]
