# Generated by Django 5.1.4 on 2025-10-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_customuser_groups_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='description',
        ),
    ]
