# Generated by Django 5.1.4 on 2025-10-21 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_customuser_groups_custom_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='半角英数字で正しいメール形式を入力してください。', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, help_text='数字とハイフンのみ使用できます。', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号'),
        ),
    ]
