# Generated by Django 5.1.4 on 2025-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_customuser_email_alter_customuser_postal_code_and_more'),
        ('tenant_mst', '0005_rename_contact_email_tenant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='employment_end_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(choices=[('1', '在職中'), ('2', '休職中'), ('3', '退職')], default='1', help_text='現在の雇用状態を選択してください。', max_length=1, verbose_name='雇用状態'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(help_text='100文字以内で入力してください。', max_length=100, verbose_name='グループ名'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'group_name'), name='unique_tenant_groupname'),
        ),
    ]
