# Generated by Django 5.1.4 on 2025-06-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_alter_customuser_gender_alter_customuser_postal_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.CharField(choices=[('0', '特権'), ('1', '一般'), ('2', '参照'), ('3', 'ゲスト')], default='2', max_length=1, verbose_name='権限'),
        ),
    ]
