# Generated by Django 5.1.4 on 2025-09-29 09:41

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('username', models.CharField(max_length=50, verbose_name='ユーザーコード')),
                ('ip', models.CharField(max_length=255, validators=[login.models.validate_ip], verbose_name='IPアドレス')),
                ('access_type', models.CharField(max_length=50, verbose_name='アクセス種別')),
                ('access_at', models.DateTimeField(auto_now=True, verbose_name='アクセス日時')),
            ],
            options={
                'ordering': ['access_at', 'username'],
            },
        ),
    ]
