# Generated by Django 5.1.4 on 2025-06-19 07:06

import django.db.models.deletion
import login.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='ユーザーコード')),
                ('ip', models.CharField(max_length=255, validators=[login.models.validate_ip], verbose_name='IPアドレス')),
                ('access_type', models.CharField(max_length=50, verbose_name='アクセス種別')),
                ('access_at', models.DateTimeField(auto_now=True, verbose_name='処理日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_creater', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ['access_at', 'username'],
            },
        ),
    ]
