# Generated by Django 5.1.4 on 2025-06-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_accesslog_created_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='created_user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='accesslog',
            old_name='updated_user',
            new_name='update_user',
        ),
    ]
