# Generated by Django 5.1.4 on 2025-09-29 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='テナントコード')),
                ('tenant_name', models.CharField(help_text='企業名や団体名', max_length=255, verbose_name='テナント名')),
                ('representative_name', models.CharField(help_text='企業や団体の代表者名', max_length=255, verbose_name='代表者名')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='代表メールアドレス')),
                ('tel_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='代表電話番号')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('state', models.CharField(blank=True, max_length=5, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='市区町村')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所2')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ['tenant_code'],
            },
        ),
    ]
