# Generated by Django 5.1.4 on 2025-09-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant',
        ),
    ]
