# Generated by Django 5.1.4 on 2025-10-15 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mst', '0002_remove_tenant_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_tel_number',
            field=models.CharField(blank=True, help_text='半角数字とハイフンのみ使用できます。例：090-1234-5678（任意）', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, help_text='番地などを100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address2',
            field=models.CharField(blank=True, help_text='建物名・部屋番号などを150文字以内で入力してください。（任意）', max_length=150, null=True, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, help_text='市区町村名を50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, help_text='都道府県名を10文字以内で入力してください。（任意）', max_length=10, null=True, verbose_name='都道府県'),
        ),
    ]
