# Generated by Django 5.1.4 on 2025-10-24 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mst', '0003_remove_tenant_tel_number_tenant_contact_tel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(error_messages={'invalid': '有効なメールアドレスを入力してください。', 'unique': '同じメールアドレスが既に登録されています。'}, max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='representative_name',
            field=models.CharField(help_text='企業や団体の代表者名', max_length=100, verbose_name='代表者名'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_name',
            field=models.CharField(help_text='企業名や団体名', max_length=100, verbose_name='テナント名称'),
        ),
    ]
