# Generated by Django 5.1.4 on 2025-10-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mst', '0004_alter_tenant_contact_email_alter_tenant_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='contact_tel_number',
            new_name='tel_number',
        ),
    ]
