# Generated by Django 5.1.4 on 2025-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('partner_name', models.CharField(max_length=255, verbose_name='取引先名')),
                ('partner_name_kana', models.CharField(blank=True, max_length=255, null=True, verbose_name='取引先名（カナ）')),
                ('partner_type', models.CharField(choices=[('customer', '顧客'), ('supplier', '仕入先'), ('both', '両方')], default='customer', max_length=20, verbose_name='取引先区分')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者名')),
                ('tel_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号')),
                ('state', models.CharField(blank=True, max_length=5, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='市区町村')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所2')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
            options={
                'ordering': ['partner_name'],
            },
        ),
    ]
