# Generated by Django 5.1.4 on 2025-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0001_initial'),
        ('tenant_mst', '0003_alter_tenant_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['partner_name']},
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('tenant', 'partner_name')},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_cd',
        ),
    ]
