# Generated by Django 5.1.4 on 2025-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
    ]
