# Generated by Django 5.1.4 on 2025-09-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0003_alter_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'メールアドレスを入力してください。', 'invalid': 'メールアドレスの形式が正しくありません。', 'null': 'メールアドレスを入力してください。', 'unique': 'このメールアドレスは既に登録されています。'}, max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
    ]
