# Generated by Django 5.1.4 on 2025-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0005_alter_partner_email'),
        ('tenant_mst', '0002_remove_tenant_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(error_messages={'blank': 'メールアドレスを入力してください。', 'invalid': 'メールアドレスの形式が正しくありません。', 'null': 'メールアドレスを入力してください。', 'unique': 'このメールアドレスは既に登録されています。'}, max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('tenant', 'partner_name', 'email')},
        ),
    ]
