# Generated by Django 5.1.4 on 2025-10-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0006_alter_partner_unique_together_alter_partner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=255, verbose_name='取引先名称'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name_kana',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='取引先名称（カナ）'),
        ),
    ]
