# Generated by Django 5.1.4 on 2025-10-01 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0007_alter_partner_partner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='半角数字のみを入力してください。', regex='^\\d+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tel_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='半角数字のみを入力してください。', regex='^\\d+$')], verbose_name='電話番号'),
        ),
    ]
