# Generated by Django 5.1.4 on 2025-10-14 10:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0008_remove_partner_is_active_alter_partner_postal_code_and_more'),
        ('tenant_mst', '0002_remove_tenant_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['partner_name'], 'verbose_name': '取引先', 'verbose_name_plural': '取引先マスタ'},
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(error_messages={'blank': 'メールアドレスを入力してください。', 'invalid': 'メールアドレスの形式が正しくありません。', 'null': 'メールアドレスを入力してください。', 'unique': 'このメールアドレスは既に登録されています。'}, max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('tenant', 'partner_name', 'email'), name='unique_tenant_partner_email'),
        ),
    ]
