# Generated by Django 5.1.4 on 2025-10-14 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0009_alter_partner_options_alter_partner_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='担当者名'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=100, verbose_name='取引先名称'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='取引先名称（カナ）'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
    ]
