# Generated by Django 5.1.4 on 2025-10-14 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0010_alter_partner_address_alter_partner_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, help_text='番地などを100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address2',
            field=models.CharField(blank=True, help_text='建物名・部屋番号などを150文字以内で入力してください。（任意）', max_length=150, null=True, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, help_text='市区町村名を50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, help_text='50文字以内で入力してください。（任意）', max_length=50, null=True, verbose_name='担当者名'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(error_messages={'blank': 'メールアドレスを入力してください。', 'invalid': 'メールアドレスの形式が正しくありません。', 'null': 'メールアドレスを入力してください。', 'unique': 'このメールアドレスは既に登録されています。'}, help_text='半角英数字で正しいメール形式を入力してください。例：info@example.com', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(help_text='100文字以内で入力してください。', max_length=100, verbose_name='取引先名称'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name_kana',
            field=models.CharField(blank=True, help_text='全角カタカナ100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='取引先名称（カナ）'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('customer', '顧客'), ('supplier', '仕入先'), ('both', '両方')], default='customer', help_text='取引先の区分を選択してください。（顧客・仕入先・両方）', max_length=20, verbose_name='取引先区分'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='state',
            field=models.CharField(blank=True, help_text='都道府県名を10文字以内で入力してください。（任意）', max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tel_number',
            field=models.CharField(blank=True, help_text='半角数字とハイフンのみ使用できます。例：090-1234-5678（任意）', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '数字とハイフンのみ使用できます。')], verbose_name='電話番号'),
        ),
    ]
