# Generated by Django 5.1.4 on 2025-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0011_alter_partner_address_alter_partner_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(error_messages={'blank': 'メールアドレスを入力してください。', 'invalid': 'メールアドレスの形式が正しくありません。', 'null': 'メールアドレスを入力してください。', 'unique': 'このメールアドレスは既に登録されています。'}, help_text='半角英数字で正しいメール形式を入力してください。例：info@example.com', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
