# Generated by Django 5.1.4 on 2025-10-17 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0012_alter_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
    ]
