# Generated by Django 5.1.4 on 2025-10-19 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0013_alter_partner_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ハイフンあり、またはなしで入力可能です。例：123-4567（任意）', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', '郵便番号の形式が正しくありません。')], verbose_name='郵便番号'),
        ),
    ]
