# Generated by Django 5.1.4 on 2025-09-29 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_mst', '0002_initial'),
        ('product_mst', '0002_initial'),
        ('tenant_mst', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sales_order_no', models.CharField(max_length=20, verbose_name='受注番号')),
                ('status_code', models.CharField(choices=[('DRAFT', '作成中'), ('SUBMITTED', '社内承認待ち'), ('APPROVED_IN', '社内承認済'), ('REJECTED_IN', '社内却下'), ('APPROVED_OUT', '顧客承諾'), ('REJECTED_OUT', '顧客却下'), ('READY_SHIP', '出荷待ち'), ('SHIPPED', '出荷済'), ('BILLED', '請求済'), ('PAID', '入金済'), ('CANCEL', 'キャンセル')], default='DRAFT', max_length=20)),
                ('sales_order_date', models.DateField(default=django.utils.timezone.now, verbose_name='受注日')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('total_amount', models.IntegerField(default=0, verbose_name='受注合計金額')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner_mst.partner', verbose_name='取引先')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '受注ヘッダ',
                'verbose_name_plural': '受注ヘッダ',
                'db_table': 'sales_order',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('line_no', models.IntegerField(verbose_name='行番号')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='単位')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('is_tax_exempt', models.BooleanField(default=False, verbose_name='消費税対象外')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=3, verbose_name='消費税率')),
                ('rounding_method', models.CharField(choices=[('floor', '切り捨て'), ('ceil', '切り上げ'), ('round', '四捨五入')], default='floor', max_length=10, verbose_name='丸め方法')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_mst.product', verbose_name='商品')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales_order.salesorder', verbose_name='受注ヘッダ')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenant_mst.tenant', verbose_name='所属テナント')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '受注明細',
                'verbose_name_plural': '受注明細',
                'db_table': 'sales_order_detail',
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'sales_order_no'), name='unique_sales_order_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderdetail',
            unique_together={('sales_order', 'line_no')},
        ),
    ]
