# Generated by Django 5.1.4 on 2025-09-30 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_mst', '0006_alter_partner_unique_together_alter_partner_email_and_more'),
        ('product_mst', '0002_initial'),
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner_mst.partner', verbose_name='取引先'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_mst.product', verbose_name='商品'),
        ),
    ]
