# Generated by Django 5.1.4 on 2025-09-26 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='rounding_method',
            field=models.CharField(choices=[('floor', '切り捨て'), ('ceil', '切り上げ'), ('round', '四捨五入')], default='floor', max_length=10, verbose_name='丸め方法'),
        ),
    ]
