# Generated by Django 5.1.4 on 2025-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0002_alter_salesorder_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='rounding_method',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rounding_method',
            field=models.CharField(choices=[('floor', '切り捨て'), ('ceil', '切り上げ'), ('round', '四捨五入')], default='floor', max_length=10, verbose_name='丸め方法'),
        ),
    ]
