# Generated by Django 5.1.4 on 2025-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0002_salesorder_status_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status_cd',
            field=models.CharField(choices=[('DRAFT', '作成中'), ('SUBMITTED', '社内承認待ち'), ('APPROVED_IN', '社内承認済'), ('REJECTED_IN', '社内却下'), ('APPROVED_OUT', '顧客承諾'), ('REJECTED_OUT', '顧客却下'), ('READY_SHIP', '出荷待ち'), ('SHIPPED', '出荷済'), ('BILLED', '請求済'), ('PAID', '入金済'), ('CANCEL', 'キャンセル')], default='DRAFT', max_length=20),
        ),
    ]
