# Generated by Django 5.1.4 on 2025-10-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0003_remove_salesorder_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='amount',
        ),
    ]
