# Generated by Django 5.1.4 on 2025-10-03 01:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0004_remove_salesorderdetail_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='billing_unit_price',
            field=models.IntegerField(default=1, verbose_name='請求単価'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='master_unit_price',
            field=models.IntegerField(default=1, verbose_name='マスタ単価'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status_code',
            field=models.CharField(choices=[('DRAFT', '仮作成'), ('SUBMITTED', '社内承認待ち'), ('APPROVED', '社内承認済'), ('REJECTED_IN', '社内却下'), ('CONFIRMED', '顧客承諾済'), ('REJECTED_OUT', '顧客却下'), ('CANCELED', 'キャンセル')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.10'), '10%'), (Decimal('0.08'), '8%')], decimal_places=2, default=Decimal('0.10'), max_digits=3, verbose_name='消費税率'),
        ),
    ]
