# Generated by Django 5.1.4 on 2025-10-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0005_remove_salesorderdetail_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderdetail',
            name='unit',
        ),
    ]
