# Generated by Django 5.1.4 on 2025-10-06 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales_order', '0006_remove_salesorderdetail_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='reference_groups',
            field=models.ManyToManyField(blank=True, related_name='referenced_sales_orders', to='auth.group', verbose_name='参照グループ'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='reference_users',
            field=models.ManyToManyField(blank=True, related_name='referenced_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='参照ユーザー'),
        ),
    ]
