# Generated by Django 5.1.4 on 2025-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0007_salesorder_reference_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status_code',
            field=models.CharField(choices=[('DRAFT', '仮作成'), ('SUBMITTED', '社内承認待ち'), ('APPROVED', '社内承認済'), ('REJECTED_IN', '社内却下'), ('CONFIRMED', '顧客承諾済'), ('REJECTED_OUT', '顧客却下'), ('CANCELED', 'キャンセル')], default='DRAFT', max_length=50),
        ),
    ]
