# Generated by Django 5.1.4 on 2025-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0009_alter_salesorder_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納入日'),
        ),
    ]
