# Generated by Django 5.1.4 on 2025-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0010_salesorder_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='納入予定日'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='納入場所'),
        ),
    ]
