# Generated by Django 5.1.4 on 2025-10-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0011_remove_salesorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='顧客コメント'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='承認者コメント'),
        ),
    ]
