# Generated by Django 5.1.4 on 2025-10-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0012_salesorder_customer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status_code',
            field=models.CharField(choices=[('DRAFT', '見積書：仮作成'), ('QUOTATION_SUBMITTED', '見積書：承認中'), ('QUOTATION_APPROVED', '見積書：社内承認済'), ('QUOTATION_CONFIRMED', '見積書：顧客承認済'), ('QUOTATION_REJECTED_IN', '見積書：社内却下'), ('QUOTATION_REJECTED_OUT', '見積書：顧客却下'), ('ORDER_SUBMITTED', '注文書：社内承認中'), ('ORDER_APPROVED', '注文書：社内承認済'), ('ORDER_CONFIRMED', '契約済'), ('ORDER_REJECTED_IN', '注文書：社内却下'), ('ORDER_REJECTED_OUT', '注文書：顧客却下'), ('CANCELED', 'キャンセル')], default='DRAFT', max_length=50),
        ),
    ]
