# Generated by Django 5.1.4 on 2025-10-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0013_alter_salesorder_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer_comment',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='manager_comment',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_customer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='注文書_顧客コメント'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='注文書_承認者コメント'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quotation_customer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='見積書_顧客コメント'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quotation_manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='見積書_承認者コメント'),
        ),
    ]
