# Generated by Django 5.1.4 on 2025-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0015_alter_salesorder_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='納入場所'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_customer_comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='注文書_顧客コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_manager_comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='注文書_承認者コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation_customer_comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='見積書_顧客コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation_manager_comment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='見積書_承認者コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
    ]
