# Generated by Django 5.1.4 on 2025-10-14 14:46

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales_order', '0016_alter_salesorder_delivery_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_due_date',
            field=models.DateField(blank=True, help_text='納入予定日を指定してください。（任意）', null=True, verbose_name='納入予定日'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_place',
            field=models.CharField(blank=True, help_text='納入先の住所や場所名を100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='納入場所'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_customer_comment',
            field=models.TextField(blank=True, help_text='顧客からの注文書へのコメント（任意）', max_length=100, null=True, verbose_name='注文書_顧客コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_manager_comment',
            field=models.TextField(blank=True, help_text='社内承認者が注文書に対して残すコメント（任意）', max_length=100, null=True, verbose_name='注文書_承認者コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation_customer_comment',
            field=models.TextField(blank=True, help_text='顧客からの見積書へのコメント（任意）', max_length=100, null=True, verbose_name='見積書_顧客コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='quotation_manager_comment',
            field=models.TextField(blank=True, help_text='社内承認者が見積書に対して残すコメント（任意）', max_length=100, null=True, verbose_name='見積書_承認者コメント'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='reference_groups',
            field=models.ManyToManyField(blank=True, help_text='この受注を参照できるユーザーグループを選択してください。（任意）', related_name='referenced_sales_orders', to='auth.group', verbose_name='参照グループ'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='reference_users',
            field=models.ManyToManyField(blank=True, help_text='この受注を参照できる社内ユーザーを選択してください。（任意）', related_name='referenced_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='参照ユーザー'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, help_text='特記事項や注意点を100文字以内で入力してください。（任意）', max_length=100, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='rounding_method',
            field=models.CharField(choices=[('floor', '切り捨て'), ('ceil', '切り上げ'), ('round', '四捨五入')], default='floor', help_text='明細金額の端数処理方法を選択してください。', max_length=10, verbose_name='丸め方法'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='受注日を選択してください。未指定の場合は当日が自動設定されます。', verbose_name='受注日'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status_code',
            field=models.CharField(choices=[('DRAFT', '見積書：仮作成'), ('QUOTATION_SUBMITTED', '見積書：提出済'), ('QUOTATION_APPROVED', '見積書：社内承認済'), ('QUOTATION_CONFIRMED', '見積書：顧客承認済'), ('QUOTATION_REJECTED_IN', '見積書：社内却下'), ('QUOTATION_REJECTED_OUT', '見積書：顧客却下'), ('ORDER_SUBMITTED', '注文書：提出済'), ('ORDER_APPROVED', '注文書：社内承認済'), ('ORDER_CONFIRMED', '契約済'), ('ORDER_REJECTED_IN', '注文書：社内却下'), ('ORDER_REJECTED_OUT', '注文書：顧客却下'), ('CANCELED', 'キャンセル')], default='DRAFT', max_length=50, verbose_name='ステータス'),
        ),
    ]
