# Generated by Django 5.1.4 on 2025-10-15 01:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0017_alter_salesorder_delivery_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='この受注を担当する社内ユーザーを選択してください。（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_order_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='受注日を指定してください。', verbose_name='受注日'),
        ),
    ]
