# Generated by Django 5.1.4 on 2025-10-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_customuser_groups_custom_alter_customuser_groups'),
        ('sales_order', '0019_approvaltoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='reference_groups',
            field=models.ManyToManyField(blank=True, help_text='この受注を参照できるユーザーグループを選択してください。（任意）', related_name='referenced_sales_orders', to='register.usergroup', verbose_name='参照グループ'),
        ),
    ]
