# Generated by Django 5.1.4 on 2025-10-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0020_alter_salesorder_reference_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='is_visible_all',
            field=models.BooleanField(default=False, help_text='チェックを入れると、この受注を全社員が参照できます。', verbose_name='全社参照可'),
        ),
    ]
