# Generated by Django 5.1.4 on 2025-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0021_salesorder_is_visible_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='is_visible_all',
            field=models.BooleanField(default=False, help_text='「全社参照可」にチェックを入れると、この受注を全社員が参照できます（参照ユーザー・グループ設定は無視されます）。', verbose_name='全社参照可'),
        ),
    ]
