# Generated by Django 5.1.4 on 2025-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0022_alter_salesorder_is_visible_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='billing_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='請求単価'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='master_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='マスタ単価'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量'),
        ),
    ]
